export const hasiltestList = [
  {
    id: 1,
    status: 'Tidak Cemas',
    colorstatus: '#12C20F',
    statusPic: 'images/hasiltest-images/tidakcemas-images.svg',
    tips1: 'Selamat saat ini anda sedang tidak dalam kondisi kecemasan terus jaga kondisi ini dengan terus menjaga kesehatan diri anda, menjaga dengan menjalankan pola hidup sehat, dan jangan lupa untuk memenuhi kebutuhan diri baik kebutuhan rohani dengan selalu tidak lupa beribadah dan kebutuhan jasmani yakni mengkonsumsi makanan sehat dan bergizi.',
    tips2:'Kondisi terbaik anda saat ini dapat dipertahankan dengan terus melakukan hal-hal atau aktivitas yang menjadi kesukaan anda, dan mempertahankan maupun melakukan kebiasaan baik serta bermanfaat yang anda miliki. Tentu tak lupa disarankan untuk melakukan hal-hal baru lainnya yang dapat mengembangkan diri anda kedepannya, pertahankan!',
    tips3:'Kondisi yang baik bukan berarti setelahnya mengesampingkan semua aspek. Anda dapat juga melakukan pencegahan terhadap kondisi tak terduga yang akan datang dengan mempersiapkan diri lebih lagi dengan seperti terus meningkatkan kualitas diri, sehingga mampu mengatasi masalah yang akan datang nantinya.',
    tips4:'Lakukan check up secara berkala terhadap diri anda agar terus mengetahui kondisi terbaru dari diri anda. Check up dapat berupa medical check up dengan melalui dokter pribadi, klinik, hingga rumah sakit hal ini guna mengetahui kesehatan secara fisik dari diri anda. Kemudian juga psikologi check up yang berguna mengetahui lebih detail terkait kondisi kesehatan mental anda.',
  },
  {
    id: 2,
    status: 'Kecemasan Ringan',
    colorstatus: '#FFE600',
    statusPic: 'images/hasiltest-images/kecemasanringan-images.svg',
    tips1: 'Saat ini anda mengalami kecemasan ringan. Tetap tenang dan berfikir positif adalah kunci karena tingkat kecemasan ini justru membuat anda menjadi waspada dan meningkatkan perhatian pada hal-hal yang anda cemaskan. Usahakan diri anda tetap dalam kendali dan lakukan refleksi diri dengan melihat hal-hal apa yang membuat diri anda cemas lalu memulai mencari solusi dari hal-hal tersebut.',
    tips2:'Anda dapat melakukan beberapa hal berikut seperti dengan sedikit melakukan peregangan pada tubuh anda. Cobalah untuk tarik nafas dalam-dalam melalui hidung tahan sejenak lalu hembuskan lewat mulut. Kemudian jangan lupa untuk mengkonsumsi air yang cukup bagi tubuh anda.',
    tips3:'Sedikit merilekskan diri bukanlah hal yang salah anda dapat mengambil waktu sejenak dengan melakukan kembali aktivitas dan hal-hal yang yang menjadi kesukaan anda. Mulailah bersosialiasi dengan lingkungan sekitar anda seperti bergabung dengan komunitas yang berdampak positif terhadap diri anda.',
    tips4:'Kecemasan saat ini bukanlah masalah besar bagi diri anda, karena yakinlah anda masih mampu memecahkan masalah yang ada. Jangan lupa untuk memberikan waktu istirahat yang cukup bagi diri anda, kemudian menerapkan pola hidup sehat dengan makan makanan sehat dan bergizi serta mulai untuk rutin berolahraga.',
  },
  {
    id: 3,
    status: 'Kecemasan Sedang',
    colorstatus: '#FF9900',
    statusPic: 'images/hasiltest-images/kecemasansedang-images.svg',
    tips1: 'Saat ini anda mengalami kecemasan sedang lakukan hal berikut tarik nafas dalam-dalam melalui hidung tahan sejenak lalu hembuskan lewat mulut dan jangan lupa mengkonsumsi air yang cukup. Anda juga dapat melakukan relaksasi otot atau peregangan otot sejenak.Tanamkan pada diri anda bahwa anda mampu melewati hal yang membuat anda cemas saat ini.',
    tips2:'Cobalah untuk memusatkan perhatian pada hal-hal yang penting saja dan mulai mengesampingkan yang tidak penting atau bukan menjadi prioritas anda. Kemudian usahakan untuk memberikan waktu istirahat yang cukup untuk diri anda dan mulailah untuk melakukan olahraga ringan dan rutin dilakukan.',
    tips3:'Mengambil waktu sejenak dengan melakukan kembali aktivitas dan hal-hal yang yang menjadi kesukaan anda. Seperti mendengarkan musik yang membantu anda sedikit rileks, kemudian luangkan waktu untuk bersosialiasi dengan bermain bersama teman ataupun keluarga sehingga dapat merefresh pikiran anda dari masalah-masalah yang ada.',
    tips4:'Jika anda merasa sakit pada tubuh anda segeralah untuk periksa ke dokter, klinik, ataupun rumah sakit hal ini guna melakukan pencegahan terhadap gejala maupun dampak yang muncul yang akan mempengaruhi kondisi tubuh anda. Jika kondisi tersebut terkait psikis maka mulailah berkonsultasi dengan psikolog ataupun psikiater.',
  },
  {
    id: 4,
    status: 'Kecemasan Berat',
    colorstatus: '#FA451D',
    statusPic: 'images/hasiltest-images/kecemasanberat-images.svg',
    tips1: 'Saat ini anda mengalami kecemasan berat lakukan hal berikut tarik nafas dalam-dalam melalui hidung tahan sejenak lalu hembuskan lewat mulut dan jangan lupa mengkonsumsi air yang cukup. Anda wajib untuk istirahat untuk mengurangi keteganganmu. Lakukan teknik relaksasi (olahraga ringan, yoga dan semacamnya). Lakukan teknik pengaturan pernapasan.Terkadang dengan mendengarkan musik atau melakukan hal-hal kesukaan dapat membuat anda rileks.',
    tips2:'Mulailah untuk bercerita terkait kecemasan ataupun masalah anda kepada keluarga maupun orang terpercaya anda. Jangan malu untuk melakukan sharing kepada orang lain karena bukan melulu terkait solusi yang ada namun dengan berceritapun sudah mampu membuat anda sedikit tenang dan rileks.',
    tips3:'Kemudian luangkan waktu untuk bersosialiasi dengan bermain bersama teman, keluarga, ataupun bergabung dengan komunitas sehingga dapat merefresh pikiran anda dari masalah-masalah yang ada.',
    tips4:'Jika anda merasa sakit pada tubuh anda segeralah untuk periksa ke dokter, klinik, ataupun rumah sakit hal ini guna melakukan pencegahan terhadap gejala maupun dampak yang muncul yang akan mempengaruhi kondisi tubuh anda. Jika kondisi tersebut terkait psikis dan juga berkepanjangan, diharapkan untuk mencari bantuan ahli (psikolog) agar masalah yang kamu hadapi tidak melebar kemana-mana, yang dapat mengakibatkan gangguan psikologis lebih dalam.',
  },
  {
    id: 5,
    status: 'Panic',
    colorstatus: '#FF0000',
    statusPic: 'images/hasiltest-images/panic-images.svg',
    tips1: 'Saat ini anda mengalami panic lakukan hal berikut tarik nafas dalam-dalam melalui hidung tahan sejenak lalu hembuskan lewat mulut dan jangan lupa mengkonsumsi air yang cukup. Anda wajib untuk istirahat untuk mengurangi keteganganmu. Lakukan teknik relaksasi (olahraga ringan, yoga dan semacamnya). Lakukan teknik pengaturan pernapasan.Terkadang dengan mendengarkan musik atau melakukan hal-hal kesukaan dapat membuat anda rileks.',
    tips2:'Mulailah untuk bercerita terkait kecemasan ataupun masalah anda kepada keluarga maupun orang terpercaya anda. Jangan malu untuk melakukan sharing kepada orang lain karena bukan melulu terkait solusi yang ada namun dengan berceritapun sudah mampu membuat anda sedikit tenang dan rileks.',
    tips3:'Kemudian luangkan waktu untuk bersosialiasi dengan bermain bersama teman, keluarga, ataupun bergabung dengan komunitas sehingga dapat merefresh pikiran anda dari masalah-masalah yang ada.',
    tips4:'Jika anda merasa sakit pada tubuh anda segeralah untuk periksa ke dokter, klinik, ataupun rumah sakit hal ini guna melakukan pencegahan terhadap gejala maupun dampak yang muncul yang akan mempengaruhi kondisi tubuh anda. Jika kondisi tersebut terkait psikis dan juga berkepanjangan, diharapkan untuk mencari bantuan ahli (psikolog) agar masalah yang kamu hadapi tidak melebar kemana-mana, yang dapat mengakibatkan gangguan psikologis lebih dalam.',
  },
];